spring.application.name=demo

# Nome da aplicação
spring.application.name=demo

# Configurações de conexão com o banco em memória H2
spring.datasource.url=jdbc:h2:mem:folhapagamento_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilita o console web do banco H2 
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# O Hibernate vai criar e atualizar as tabelas automaticamente baseado nas nossas classes Entity
spring.jpa.hibernate.ddl-auto=update

# Mostra no console do VS Code os comandos SQL que o Spring está executando 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true